### PR TITLE
Master

### PR DESCRIPTION
**Pull request by stephortiz**
Reads better for screenreader.  Should test this method of displaying logo for screenreader

### CODE REVIEW

**Comment by bdm4** [comment]
You forked the wrong repo :) At this point there is nothing different 
between Case/Master and FPB/Master as we merged on friday.

You want to fork:
https://github.com/CaseWesternReserveUniversity/CaseTemplates
Ben

**Comment by bdm4** [comment]
We aren't going to merge in changes from aurora into fpb/master. The only time a pull request is required is when a new version of the templates is out, and you want to update your site with the latest.  It's a little backwards I know.

**Comment by stephortiz** [comment]
My fault ben, i was getting used to the interface.  i sent a few separately

**Comment by bdm4** [comment]
No problem! It's an uphill climb and will take some getting used too. But once we get on the same page fireworks will start to happen :+1: You can already see one of the major  advantages by this simple communication. :trophy:

**Pull request closed without merging**
