### PR TITLE
Caption

### PR DESCRIPTION
**Pull request by stephortiz**
Text Align left

### CODE REVIEW

**Comment by bdm4** [comment]
Not merging aurora change code onto fpb... 

Some advice and stuff :smile:  
1) Don't edit content the case-templates folder. Subsequent versions can overwrite these changes, then you'll have to do some conflict management. Not fun on large amounts of changes. 

2) Don't edit minimization files. In the head-content.shtml file there is a commented out block for debugging css. Once you made changes to the debugging css file and ready to goto production then you compile your debugging css into minimization form. 

3) Ask questions. This version of the template is nothing like the one on T4. It's more bootstrap with a case theme applied. That's why the demo folder is just that, because with boot strap there is no more a 3 column template, it's a NxM table. Theoretically you can have a 24 column template. 

4) Keep playing that's the only way to get this. 

5) Keep in mind the templates are organic. They are always changing to meet demand, performance, scalability, and of course, bug fixes.

**Comment by stephortiz** [comment]
Are these being pushed to your version for some reason?

**Comment by bdm4** [comment]
No. Just pull request is being made, it's a little confusing.
I can also request do the same to you as well.

So If update fpb/master from Case...University/master. I can then 
request to push fpb/master to cwru/master (your repo). This is a little 
confusing.. I wonder if I can create a repo under the 
CaseWesternReserveUniversty org called Aurora. That would make things 
clearer. It doesn't matter for now as long as you are in playing and 
don't plan on escalating this to production.

Ben

**Comment by stephortiz** [comment]
Nothing from here is going be pushed directly to a live site

**Comment by stephortiz** [comment]
I sent a few singular changes I thought you'd want.  I guess it sent everything?

**Pull request closed without merging**
